# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: "cr.yandex/crp3pink8cvakpdofcj2/stg_service"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2022-11-21-r1"

containerPort: 5000

config:
  KAFKA_HOST: "rc1a-1i0llfi9v534egjb.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "1234567890"
  KAFKA_CONSUMER_GROUP: "main-consumer-group"
  KAFKA_SOURCE_TOPIC: "order-service_orders"
  KAFKA_STG_SERVICE_ORDERS_TOPIC: "stg-service-orders"

  PG_WAREHOUSE_HOST: "rc1b-zesu0w2mzt9f5ay4.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "user_db"
  PG_WAREHOUSE_PASSWORD: "1234567890"

  REDIS_HOST: "rc1d-becn2ado3lp11fon.mdb.yandexcloud.net"
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "1234567890"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
