# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: "cr.yandex/crp8rf1hih4ih3gcms0g/dds_service"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2024-02-12-r7"

containerPort: 5000

config:
  EXAMPLE_ENV1: "value1"
  EXAMPLE_ANOTHER_ENV2: "value2"

  KAFKA_HOST: "rc1a-g0u8j8ghlfr0sd0f.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "S2149MmM"
  KAFKA_CONSUMER_GROUP: "main-consumer-group"
  KAFKA_SOURCE_TOPIC: "stg-service-orders"
  KAFKA_DESTINATION_TOPIC: "dds-service-orders"

  PG_WAREHOUSE_HOST: "rc1b-rxbnfoaca13tatvb.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "matthew_ms"
  PG_WAREHOUSE_PASSWORD: "S2149Mm!"

  BATCH_SIZE: "100"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
